// <auto-generated />
namespace TestLab6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class repeat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(repeat));
        
        string IMigrationMetadata.Id
        {
            get { return "202103230508054_repeat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
